### ISSUE TITLE
Improve interaction responses

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/lc-dailies#11]
All Discord application command errors result in the Discord user seeing an error message, "This interaction failed".

<img width="132" alt="image" src="https://github.com/acmcsufoss/lc-dailies/assets/31261035/1713f6a3-a499-4f0c-8ac0-581bcf7491d7">

Additionally, successful messages are not ephemeral. So, successful messages are shown to everyone even though this may not be desired by our players.

Follows up: <https://discord.com/channels/710225099923521558/802314440602943518/1146698548000325662>.

**Comment by karnikaavelumani** [comment]
I can take up this issue!

Just to clarify,
<img width="649" alt="image" src="https://github.com/acmcsufoss/lc-dailies/assets/60043611/c35bccf3-986f-4439-84fc-187b9aae1a9a">
These errors written in this file will print it out in the actual console as opposed to discord correct?

**Comment by EthanThatOneKid** [comment]
> These errors written in this file will print it out in the actual console as opposed to discord correct?

Precisely! :godmode:
